### ISSUE TITLE
Uncaught TypeError: isListItem is not a function

### ISSUE THREAD

**Issue by WestFlame** [burodepeper/language-markdown#161]
[Enter steps to reproduce below:]

1. I just wanted to move list asterisk to sublevel (with `TAB` key) and this exception appeared

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [language-markdown](https://github.com/burodepeper/language-markdown) package, v0.19.0

### Stack Trace

Uncaught TypeError: isListItem is not a function

```
At /home/miki/.atom/packages/language-markdown/lib/main.coffee:176

TypeError: isListItem is not a function
    at Object.outdentListItem (/home/miki/.atom/packages/language-markdown/lib/main.coffee:176:28)
    at atom-text-editor.subscriptions.add.atom.commands.add.markdown:outdent-list-item (/home/miki/.atom/packages/language-markdown/lib/main.coffee:57:104)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:259:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:24.2.0 pane:show-previous-item (div.panels-item)
     -0:20.2.0 markdown-preview:toggle (input.hidden-input)
     -0:16.4.0 core:close (input.hidden-input)
     -0:12.2.0 window:focus-next-pane (input.hidden-input)
     -0:11.4.0 core:close (div.markdown-preview.native-key-bindings)
 13x -0:09.5.0 core:move-down (input.hidden-input)
 23x -0:05.6.0 core:move-up (input.hidden-input)
  2x -0:03.9.0 pane:show-previous-item (input.hidden-input)
     -0:01.6.0 core:move-down (input.hidden-input)
  2x -0:01.3.0 core:move-up (input.hidden-input)
     -0:00.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:00.7.0 editor:newline (input.hidden-input)
     -0:00.0 snippets:previous-tab-stop (input.hidden-input)
     -0:00.0 markdown:outdent-list-item (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "language-python"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.3.9 (active)
autocomplete-paths, v1.0.5 (active)
exception-reporting, v0.40.1 (active)
file-icons, v2.0.9 (active)
git-time-machine, v1.5.4 (inactive)
highlight-selected, v0.12.0 (active)
language-docker, v1.1.7 (active)
language-latex, v1.0.0 (active)
language-markdown, v0.19.0 (active)
language-todotxt, v0.6.1 (active)
latextools, v0.8.5 (active)
MagicPython, v1.0.3 (active)
markdown-scroll-sync, v2.1.2 (active)
metrics, v1.1.2 (active)
minimap, v4.26.6 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.5.0 (active)
pdf-view, v0.54.0 (active)
sync-settings, v0.8.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (active)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by burodepeper** [comment]
Thank you for reporting. I've seen this error too, but it appears to come and go. I'll look into it, and hope to release a patch later today.

**Comment by burodepeper** [comment]
I've just published v0.19.1 that should fix this. Apparently mixing CoffeeScript with JavaScript causes some issues. Let me know if your issue is fixed with this.

**Comment by WestFlame** [comment]
Thanks! I've updated and all is working fine :).

**Comment by burodepeper** [comment]
Good! Thanks again for reporting.
