### ISSUE TITLE
Failed to load the language-markdown package

### ISSUE THREAD

**Issue by pbalduino** [burodepeper/language-markdown#176]
Hi there

I got this error after install `language-markdown` package via Atom interface.

I'm using 1.15.0 on MacOS X 10.10.

I tried to install the so called `season`, but I didn't found that package.

Thanks

```
**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.5
**Thrown From**: [language-markdown](https://github.com/burodepeper/language-markdown) package 0.20.0


### Stack Trace

Failed to load the language-markdown package

At Cannot find module 'season'

Error: Cannot find module 'season'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/language-markdown/lib/main.coffee:4:8)
    at /packages/language-markdown/lib/main.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
     -0:12.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
autoclose-html 0.23.0 
busy-signal 1.3.0 
intentions 1.1.2 
language-markdown 0.20.0 
language-rspec 0.6.1 
language-vue 0.21.2 
linter 2.1.2 
linter-ruby 1.2.5 
linter-ui-default 1.2.2 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
project-manager 3.3.4 
rails-rspec 0.3.2 
rails-snippets 2.15.0 
react 0.16.2 
rspec-tree-runner 1.0.4 
ruby-bundler 0.3.0 
```

**Comment by burodepeper** [comment]
Did you install language-markdown via the Atom interface or via the command line?

**Comment by pbalduino** [comment]
Hi @burodepeper. Thank you for the prompt answer.

I installed via Atom interface. I updated the issue text.

Regards.

**Comment by pbalduino** [comment]
Sorry, I didn't read the manual before install.

I just uninstalled, disabled `language-gfm`, closed Atom, reopened, reinstalled and so far I did't see the error again.

**Comment by burodepeper** [comment]
No problem, and that's good to hear. I think that maybe season couldn't be loaded from NPM on your first attempt, and the second attempt was successful. Enjoy the package, hope you don't run into other issues ;)

**Comment by EdiMund** [comment]
Hi team,

I installed the package via the Atom interface. I followed the instructions (disabled language-gfm), closed Atom and reopened. Reboot my PC and still I am experiencing the same issue described above (Failed to load the language-markdown package At Cannot find module 'season').

What would you recommend me to do?

Disabling all language packages also does not work.

Thanks
:-)

**Comment by burodepeper** [comment]
@EdiMund What version of Atom are you using?
