### ISSUE TITLE
Uncaught TypeError: Cannot read property 'editor' of undefined

### ISSUE THREAD

**Issue by xialei2200** [burodepeper/language-markdown#245]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [language-markdown](https://github.com/burodepeper/language-markdown) package 0.29.0

### Stack Trace

Uncaught TypeError: Cannot read property 'editor' of undefined

```
At C:\Users\xialei\.atom\packages\language-markdown\lib\main.js:205

TypeError: Cannot read property 'editor' of undefined
    at Object.indentListItem (/packages/language-markdown/lib/main.js:205:13)
    at /packages/language-markdown/lib/main.js:190:111)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:350017)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1212981)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:1209115)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:285196)
```

### Commands

```
     -0:08.2.0 markdown:indent-list-item (input.hidden-input)
     -0:08.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:08.2.0 snippets:expand (input.hidden-input)
     -0:08.2.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
language-markdown 0.29.0 
markdown-image-paste 2.5.2 
markdown-preview-plus 3.8.1 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.1 
pdf-view 0.71.0 
```

**Comment by burodepeper** [comment]
Thanks for the report.
What steps do I need to take to reproduce the issue?
