### ISSUE TITLE
Failed to load the language-markdown package

### ISSUE THREAD

**Issue by ihaiker** [burodepeper/language-markdown#56]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Mac OS X 10.10.5
**Thrown From**: [language-markdown](https://github.com/burodepeper/language-markdown) package, v0.7.0

### Stack Trace

Failed to load the language-markdown package

```
At Cannot find module 'season'

Error: Cannot find module 'season'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/Users/haiker/.atom/packages/language-markdown/lib/main.coffee:2:8)
    at Object.<anonymous> (/Users/haiker/.atom/packages/language-markdown/lib/main.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:663:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:390:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:682:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:85:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/Users/haiker/",
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
language-gradle, v0.0.3
language-markdown, v0.7.0
language-sql, v0.20.0

# Dev
No dev packages
```

**Comment by burodepeper** [comment]
@ihaiker Is this issue fixed for you with the latest release of Atom? There was a bug in Atom which caused a lot of packages not to be able to be installed/loaded.

**Comment by burodepeper** [comment]
I'm closing this because of lack of verification and/or ways of replicating. It was probably because of a bug in a particular version of Atom that has since been fixed.
