### ISSUE TITLE
Failed to load the language-markdown package

### ISSUE THREAD

**Issue by ideepinos** [burodepeper/language-markdown#95]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Deepin 15.1
**Thrown From**: [language-markdown](https://github.com/burodepeper/language-markdown) package, v0.11.0

### Stack Trace

Failed to load the language-markdown package

```
At EACCES: permission denied, scandir '/home/deepin/.atom/packages/language-markdown/keymaps'

Error: EACCES: permission denied, scandir '/home/deepin/.atom/packages/language-markdown/keymaps'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.fsPlus.listSync (/usr/share/atom/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:171:18)
    at Package.module.exports.Package.getKeymapPaths (/usr/share/atom/resources/app.asar/src/package.js:414:19)
    at Package.module.exports.Package.loadKeymaps (/usr/share/atom/resources/app.asar/src/package.js:378:29)
    at /usr/share/atom/resources/app.asar/src/package.js:110:19
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-markdown, v0.11.0
markdown-scroll-sync, v2.1.2

# Dev
No dev packages
```

**Comment by burodepeper** [comment]
Thanks for reporting @ideepinos 
Did this occur during/after installing? Is it a persistent error, or did it just occur a single time?

From what I can see in the stack trace, this isn't directly related to this package, but rather unfortunately originated there. Do you have any other occasional file system related issues?

**Comment by burodepeper** [comment]
Closing this as a probable _freak occurrence_.
